import type { Budget } from './types';
import { generateId } from './id';

export function createEmptyBudget(overrides?: Partial<Budget>): Budget {
  const now = new Date().toISOString();
  const defaults: Budget = {
    id: generateId(),
    companyId: null,
    clientId: null,
    serviceType: '',
    serviceCategory: '',
    description: '',
    projectName: '',
    projectDescription: '',
    siteAddress: '',
    city: '',
    measurements: {},
    quantities: {},
    options: {},
    calculated: {
      floorArea: null,
      perimeter: null,
      wallArea: null,
      volume: null,
      linearMeters: null,
    },
    estimatedDays: null,
    daysCalculationMode: 'manual',
    productivityPerDay: null,
    teamDailyCost: null,
    laborCost: null,
    workerCost: null,
    helperCost: null,
    workerDailyRate: null,
    helperDailyRate: null,
    numberOfHelpers: null,
    transportCost: 0,
    foodCost: 0,
    fuelCost: 0,
    toolCost: 0,
    otherCost: 0,
    expenseCost: 0,
    riskReservePercent: null,
    riskReserve: 0,
    materialCost: 0,
    materialSellingPrice: 0,
    totalCost: 0,
    minimumMargin: null,
    recommendedMargin: null,
    fullMargin: null,
    minimumPrice: null,
    recommendedPrice: null,
    fullPrice: null,
    effectiveUnitPrice: null,
    pricingVersion: 'v1',
    selectedPriceType: null,
    customPrice: null,
    discount: 0,
    finalPrice: null,
    paymentMethod: '',
    paymentTerms: [],
    includedServices: [],
    excludedServices: [],
    agreedDays: null,
    validityDays: 30,
    expiresAt: null,
    approvalStatus: 'pending',
    approvedAt: null,
    rejectedAt: null,
    status: 'draft',
    projectMode: 'simple',
    stages: [],
    materials: [],
    createdAt: now,
    updatedAt: now,
  };

  return { ...defaults, ...overrides };
}
